name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          PSGALLERY_KEY: ${{ secrets.PSGALLERY_KEY }}
        shell: pwsh
        run: |
            Publish-Module -Path /adolib -NuGetApiKey $env:PSGALLERY_KEY -Verbose